### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by garrows**

### CODE REVIEW

**Comment by garrows** [comment]
Bit of a weird PR but it annoyed me. Love the project btw.

**Comment by NickColley** [comment]
Hey @garrows the website project has been moved to https://github.com/datproject/website so submit your PR there :+1:

**Comment by garrows** [comment]
Hmm ok. Done https://github.com/datproject/website/pull/10

**Comment by garrows** [comment]
Also https://github.com/maxogden/dat-data.com/pull/12 points people to the new location.

Btw for the future, github supports moving repos and will redirect people from the old location.

**Pull request closed without merging**
